[project]
name = "tower-defense-backend"
version = "0.1.0"
description = "Multiplayer Tower Defense Game Backend"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.30.0",
    "websockets>=13.0",
    "pydantic>=2.9.0",
]